name: CI Pipeline of practice application

on:
  push:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu_latest
    steps:
      - name: checkout_code
        uses: actions/checkout@v4
   
      - name: setup_nodejs
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: install_dependencies
        run: npm install  


  